name: Pull request

on: [pull_request]

jobs:
  workflow:
    name: CI/CD
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'feature/')
      || startsWith(github.head_ref, 'hotfix/')
      || startsWith(github.head_ref, 'fix/')
      || startsWith(github.head_ref, 'bugfix/')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: |
          yarn install 
          yarn audit

      - name: Prettier
        run: |
          yarn prettier:check

      - name: Lint
        run: |
          yarn lint
